force-app/main/default/objects/Interview__c/Interview__c.object-meta.xml
<CustomObject>
    <description>An interview is a conversation beetwen speaker and interviewer to measure speakere knowledge.</description>
    <label>Interview</label>
    <nameField>
        <displayFormat>IN-{0000}</displayFormat>
        <label>Interview Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Interviews</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Interview__c/fields/Session__c.field-meta.xml
<CustomField>
    <fullName>Session__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Session</label>
    <referenceTo>Session__c</referenceTo>
    <relationshipLabel>Interviews</relationshipLabel>
    <relationshipName>Interviews</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Interview_Interviewer__c/Interview_Interviewer__c.object-meta.xml
<CustomObject>
    <description>Junction object between interview and interviewers.</description>
    <label>Interview Interviewer</label>
    <nameField>
        <label>Interview Interviewer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Interview Interviewers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Interview_Interviewer__c/fields/Interview__c.field-meta.xml
<CustomField>
    <fullName>Interview__c</fullName>
    <label>Interview</label>
    <referenceTo>Interview__c</referenceTo>
    <relationshipLabel>Interview Interviewers</relationshipLabel>
    <relationshipName>Interview_Interviewers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Interview_Interviewer__c/fields/Interviewer__c.field-meta.xml
<CustomField>
    <fullName>Interviewer__c</fullName>
    <label>Interviewer</label>
    <referenceTo>Interviewer__c</referenceTo>
    <relationshipLabel>Interview Interviewers</relationshipLabel>
    <relationshipName>Interview_Interviewers</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Interviewer__c/Interviewer__c.object-meta.xml
<CustomObject>
    <description>Employee that qualified enough on a topic that Speaker preparing.</description>
    <label>Interviewer</label>
    <nameField>
        <label>Interviewer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Interviewers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Session__c/Session__c.object-meta.xml
<CustomObject>
    <description>Session or presentation of speaker on some toppic.</description>
    <label>Session</label>
    <nameField>
        <label>Session Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sessions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Session__c/fields/Topic_Technologies__c.field-meta.xml
<CustomField>
    <fullName>Topic_Technologies__c</fullName>
    <label>Topic Technologies</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Topic_Technologies</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Topic_Technologies.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Data</fullName>
    </customValue>
    <customValue>
        <fullName>Security</fullName>
    </customValue>
    <customValue>
        <fullName>Analyse</fullName>
    </customValue>
    <customValue>
        <fullName>Salesforce</fullName>
    </customValue>
    <customValue>
        <fullName>Report</fullName>
    </customValue>
    <customValue>
        <fullName>Testing</fullName>
    </customValue>
    <customValue>
        <fullName>QA</fullName>
    </customValue>
    <customValue>
        <fullName>Frond-end development</fullName>
    </customValue>
    <customValue>
        <fullName>Back-end devlopment</fullName>
    </customValue>
    <masterLabel>Topic Technologies</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/InterviewersAssignment.cls
public class InterviewersAssignment {
    @InvocableMethod(label = 'Assign Interviewers'
        description = 'Retun apropiate interviwers for this session.')
    public static void assignInterviewers(List < Interview__c > interviewList) {
        Interview__c interview = interviewList[0];
        Session__c session = [SELECT Id, Name, Topic_Technologies__c FROM Session__c WHERE Id =: interview.Session__c];
        String[] topicTechnologyList = session.Topic_Technologies__c.split(';');
        String[] requiredTopics = topicTechnologyList.clone();
        List < Interviewer__c > interviewerList = [SELECT Id, Name, Topic_Technologies__c FROM Interviewer__c];
        Integer interviewerQuantity = 0;
        for (Interviewer__c interviewer: interviewerList) {
            Boolean topicIsKnown = false;
            for (String topicTechnology: topicTechnologyList) {
                if (interviewer.Topic_Technologies__c.contains(topicTechnology)) {
                    topicIsKnown = true;
                    Integer topicIndex = requiredTopics.indexOf(topicTechnology);
                    if (topicIndex >= 0) {
                        requiredTopics.remove(topicIndex);
                    }
                }
            }
            if (topicIsKnown) {
                Interview_Interviewer__c interviewInterviewer = new Interview_Interviewer__c(
                    Interview__c = interview.Id,
                    Interviewer__c = interviewer.Id,
                    Name = interview.Name + ' - ' + interviewer.Name
                );
                insert interviewInterviewer;
                interviewerQuantity++;
            }
            if (interviewerQuantity >= 3 && requiredTopics.isEmpty()) {
                break;
            }
        }
    }
}